IS2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView


from Accounts.forms import LoginForm

urlpatterns = [
    path('clientes/', include('Cliente.urls')),
    path('access/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}),
    path('logout/', views.logout, {'next_page': '/login'}, name='logout'),
    path('', include('Accounts.urls')),
    path('proyecto/', include('Proyecto.urls')),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto/urls.py
from django.urls import path,include
from . import views
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from guardian.decorators import permission_required_or_403


# Urls del sistema
app_name = 'Proyecto'
urlpatterns = [
    path('', views.ListaProyectos.as_view(), name='listaProyectos'),
    path('crear/', views.Crear_Proyecto.as_view(), name='crearProyecto'),
    path('<int:pk>/modificar/', views.Modificar_Proyecto.as_view(), name='modificarProyecto'),
    path('<int:pk>/home/', views.HomeProyectos.as_view(), name='homeProyecto'),

    path('<int:pk>/modificar/team/', include('team.urls')),
    path('<int:pk>/sprint/', include('Sprint.urls')),
    path('<int:pk>/kanban/', include('Kanban.urls')),
    path('<int:pk>/modificar/userstories/', include('UserStory.urls')),
    path('projects/list', views.ListaProyectos, name='pro_list'),
    path('proyecto/crear', views.Crear_Proyecto.as_view(), name='pro_crear'),
    path('<int:pk>/confirmar_terminar', views.VerificarTerminarProyecto.as_view(), name='confirmar_terminarProyecto'),
    path('<int:pk>/terminar', views.CancelarProyecto, name='terminar'),
    path('<int:pk>/iniciar', views.iniciarProyectoView, name='iniciarProyecto'),

    path('<int:pk>/reporte/product_backlog', views.reporte_product_backlog, name='reporteProductBacklog'),
    path('<int:pk>/reporte/horas_totales', views.reporte_horas_trabajadas, name='reporteHorasTrabajadas'),
    path('<int:pk>/reporte/kanban', views.reporte_kanban_actual, name='reporteKanban'),

    # url(r'^team/', include('team.urls', namespace='Team'))
]

templates/pro/pro_crear.html
{% extends 'index.html' %}
{% load static %}
{% block index_content %}
 <!-- PAGE CONTENT WRAPPER -->
                <div class="page-content-wrap">

                    <div class="row">
                        <div class="col-md-12">

                            <form class="form-horizontal" method="post" >
                            {% csrf_token %}
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title"><strong>Crear proyecto</strong></h3>
{#                                    <ul class="panel-controls">#}
{#                                        <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>#}
{#                                    </ul>#}
                                </div>
                                <div class="panel-body">

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Nombre</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.nombre }}
                                            </div>
                                            <span class="help-block">Longitud maxima 100 caracteres *Campo obligatorio</span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Descripcion</label>
                                        <div class="col-md-6 col-xs-12">
                                             <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.descripcion }}
                                            </div>
                                            <span class="help-block">Longitud maxima 500 caracteres *Campo obligatorio</span>
                                        </div>
                                    </div>
                                        {{ form.errors }}

                                    </div>
                                     <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label"> Usuario Scrum Master </label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-user"></span></span>
                                                {{ form.user}}
                                            </div>
                                            <span class="help-block">Seleccione el usuario Scrum Master *Campo obligatorio</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label"> Horas de trabajo del Scrum </label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.horas_trabajadas}}
                                            </div>
                                            <span class="help-block">Designe las horas de trabajo del Scrum Master en el proyecto *Campo obligatorio</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label"> Rol asignado al Scrum </label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.rol}}
                                            </div>
                                            <span class="help-block">Seleccione un rol de proyecto al Scrum Master dentro del proyecto *Campo obligatorio</span>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label"> Cliente del Proyecto </label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-user"></span></span>
                                                {{ form.cliente}}
                                            </div>
                                            <span class="help-block">Seleccione un cliente para el proyecto *Campo obligatorio</span>
                                        </div>
                                    </div>


                                     <div class="panel-footer">
                                        <button class="btn btn-primary pull-right"  data-box="#mb-usercreate">Crear</button>
                                    </div>
                                </div>


                            </form>
                        </div>
                    </div>
                </div>
{% endblock %}

templates/pro/pro_home.html
{% extends 'index.html' %}
{% load static %}


{% block barra-superior %}
     {% load tags_permisos %}
    {% get_obj_perms user for proyecto as "context_var" %}
    <li class="xn-openable">
        <a href="#"><span class="xn-text">Kanban</span></a>
        <ul>
             {% if 'Kanban.ver_flujos' in context_var  %}
            <li><a href="{% url 'Proyecto:Kanban:visualizar' proyectoKey %}"><span class="fa fa-eye"></span>Visualizar</a></li>
            {% endif %}
            {% if 'Kanban.crear_flujo' in context_var and proyecto.estado == 2 %}
            <li><a href="{% url 'Proyecto:Kanban:crearflujo' proyectoKey %}"><span class="fa fa-plus"></span> Crear flujos</a></li>
            {% endif %}
            {% if 'Kanban.ver_flujos' in context_var  %}
            <li><a href="{% url 'Proyecto:Kanban:listarflujo' proyectoKey %}"><span class="fa fa-list-ol"></span> Listar flujos</a></li>
            {% endif %}
        </ul>
    </li>
    <li class="xn-openable">
        <a href="#"><span class="xn-text">Sprint</span></a>
        <ul>
                {% if 'Sprint.listar_sprint' in context_var  %}
                    <li><a href="{% url 'Proyecto:sprint:listaSprint' proyectoKey %}"><span class="fa fa-list-ol"></span>Listar</a></li>
                {% endif %}
                {% if 'Sprint.crear_sprint' in context_var and proyecto.estado == 2 %}
                    <li><a href="{% url 'Proyecto:sprint:crearSprint' proyectoKey %}"><span class="fa fa-plus"></span>Crear</a></li>
                {% endif %}
        </ul>
    </li>
    <li class="xn-openable">
        <a href="#"><span class="xn-text">User Stories</span></a>
        <ul>
            {% get_obj_perms user for proyecto as "context_var"  %}
                {% if 'UserStory.listar_us' in context_var %}
                    <li><a href="{% url 'Proyecto:UserStory:listaUs' proyectoKey %}"><span class="fa fa-list-ol"></span>Listar</a></li>
                {% endif %}
                {% if 'UserStory.crear_us' in context_var and proyecto.estado == 2 %}
                    <li><a href="{% url 'Proyecto:UserStory:crearUs' proyectoKey %}"><span class="fa fa-plus"></span>Crear</a></li>
                {% endif %}
        </ul>
    </li>
    <li class="xn-openable">
        <a href="#"><span class="xn-text">Team</span></a>
        <ul>
            {% get_obj_perms user for proyecto as "context_var"  %}
                {% if 'team.listar_team' in context_var %}
                    <li><a href="{% url 'Proyecto:Team:listaTeam' proyectoKey %}"><span class="fa fa-list-ol"></span> Listar</a></li>
                {% endif %}
                {% if 'team.crear_team' in context_var and proyecto.estado == 2 %}
                    <li><a href="{% url 'Proyecto:Team:crearTeam' proyectoKey %}"><span class="fa fa-plus"></span> Crear</a></li>
                {% endif %}
        </ul>
    </li>

{% endblock %}

templates/pro/pro_listar.html
{% extends 'index.html' %}
{% load static %}

{% block index_content %}
    {% load guardian_tags %}
    <!-- START RESPONSIVE TABLES -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Proyectos</strong></h3>
                    <input class="form-control" id="myInput" type="text" placeholder="Buscar proyecto">
                    <br>
                </div>

                <div class="panel-body panel-body-table">

                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-actions">
                            <thead>
                            <tr>
                                <th width="250">Nombre</th>
                                <th width="100">Descripcion</th>
                                <th width="100">Fecha inicio</th>
                                <th width="100">Fecha fin</th>
                                <th width="100">Estado</th>
                            </tr>
                            </thead>
                            <tbody id="myTable">
                            {% for proyecto in my_proyectos %}
                                {% get_obj_perms user for proyecto as "permisos" %}

                                <tr id="<pk>">
                                    {% if  proyecto.estado != 1 %}
                                        {% if proyecto in lista or user.is_superuser %}
                                            <td><strong><a href="{% url 'Proyecto:UserStory:listaUs'  proyecto.id %}">{{ proyecto.nombre }}</a></strong></td>

                                        {% else %}
                                            <td><strong>{{ proyecto.nombre }}</strong></td>
                                        {% endif %}

                                    {% else %}
                                        <td><strong class="text-center">{{ proyecto.nombre}}</strong></td>
                                    {% endif %}
                                    <td><span class="text-center">{{ proyecto.descripcion}}</span></td>
                                    {% if proyecto.fechainicio != None %}
                                        <td><span class="text-center">{{ proyecto.fechainicio}}</span></td>
                                    {% else %}
                                        <td><span class="text-center">                 </span></td>
                                    {% endif  %}
                                    {% if proyecto.fechafin != None %}
                                        <td><span class="text-center">{{ proyecto.fechafin}}</span></td>
                                    {% else %}
                                        <td><span class="text-center">                 </span></td>
                                    {% endif  %}
                                    <td><span class="text-center">{{ proyecto.get_estado_display }}</span></td>
                                    <td>
                                        {% if perms.Proyecto.iniciar_proyecto and proyecto.estado == 1 %}
                                            <a href="{% url 'Proyecto:iniciarProyecto' proyecto.id %}"><button class="btn btn-default btn-rounded btn-sm"><span class="fa fa-pencil"></span>Iniciar</button></a>
                                        {% endif %}
                                        {% if perms.Proyecto.modificar_proyecto and proyecto.estado != 3 and proyecto.estado != 4 %}
                                            <a href="{% url 'Proyecto:modificarProyecto' proyecto.id %}"><button class="btn btn-default btn-rounded btn-sm"><span class="fa fa-pencil"></span>Modificar</button></a>
                                        {% endif %}
                                        {% if perms.Proyecto.eliminar_proyecto and proyecto.estado == 2 %}
                                            <a href="{% url 'Proyecto:confirmar_terminarProyecto' proyecto.id %}">
                                                <button class="btn btn-danger btn-rounded btn-sm" ><span class="fa fa-times"></span>Terminar Proyecto</button></a>

                                        {% endif %}
                                        <a href="#" class="mb-control" data-box="#mb-detail{{ proyecto.id }}"><button class="btn btn-info"> Detalles</button></a>

                                        <a href="{% url 'Proyecto:reporteProductBacklog' proyecto.id %}"><button class="btn btn-info"> Reporte Product backlog</button></a>
                                        <a href="{% url 'Proyecto:reporteHorasTrabajadas' proyecto.id %}"><button class="btn btn-info"> Reporte Horas Trabajadas</button></a>
                                        <a href="{% url 'Proyecto:reporteKanban' proyecto.id %}"><button class="btn btn-info"> Reporte Tablero Kanban</button></a>


                                    </td>
                                </tr>
                                <!-- MESSAGE BOX-->
                                <div class="message-box animated fadeIn" data-sound="alert" id="mb-delete{{ proyecto.id }}">
                                    <div class="mb-container">
                                        <div class="mb-middle">
                                            <div class="mb-title"><span class="fa fa-trash-o"></span><strong>Eliminar</strong> ?</div>
                                            <div class="mb-content">
                                                <p>Estas seguro que deseas eliminar {{ proyecto.nombre }}?</p>
                                            </div>
                                            <div class="mb-footer">
                                                <div class="pull-right">
                                                    <form action="{%  url 'Proyecto:confirmar_terminarProyecto' proyecto.id %}" method="post">
                                                        {% csrf_token %}
                                                        <input type="submit" value="Confirm"/>
                                                        <button class="btn btn-light btn-small mb-control-close">No</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="message-box animated"  id="mb-detail{{ proyecto.id }}">
                                    <div class="mb-container">
                                        <div class="mb-middle">
                                            <div class="mb-title"><strong>{{ proyecto.nombre}}</strong></div>
                                            <div class="mb-content">
                                                <p>Descripcion:  {{ proyecto.descripcion }}</p>
                                                <p>Fecha inicio: {{ proyecto.fechainicio }}</p>
                                                <p>Fecha fin: {{ proyecto.fechafin }}</p>
                                                {% if proyecto.cliente != None %}
                                                    <p>Cliente: {{ proyecto.cliente.nombre }} {{ proyecto.cliente.apellido }}</p>
                                                {% else %}
                                                    <p>Cliente: Cliente no asignado</p>
                                                {% endif %}
                                                <p>Team members:
                                                    {% for member in proyecto.team_set.all %}
                                                        * {{ member.user.username }} </br>
                                                    {% endfor %} </p>
                                                <div class="pull-right">
                                                    <button class="btn btn-light btn-small mb-control-close">Cerrar</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!-- END MESSAGE BOX-->
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
    <!-- END RESPONSIVE TABLES -->
{% endblock %}

templates/pro/pro_menu.html
{% extends 'index.html' %}
{% load static %}

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Gestpro</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Sprints</a></li>
      <li><a href="#">Team</a></li>
      <li><a href="#">Kanban</a></li>
    </ul>
  </div>
</nav>

templates/pro/pro_mod.html
{% extends 'index.html' %}
{% load static %}


{% block index_content %}

    <div class="page-content-wrap">

        <div class="row">
            <div class="col-md-12">

                <form class="form-horizontal" method="post" >
                    {% csrf_token %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 style="text-align:right; font-size:100%;" class="col-12 align-right"><strong>Trabajando en:</strong> {{ proyecto.nombre }} </h4>
                            <h3 class="panel-title"><strong>Modificar</strong></h3>
                        </div>


                        <div class="panel-body">
                            <div class="form-group">
                                <label class="col-md-3 col-xs-12 control-label">Nombre</label>
                                <div class="col-md-6 col-xs-12">
                                    <div class="input-group">
                                        <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                        {{ form.nombre }}
                                    </div>
                                    <span class="help-block">Longitud maxima 100 caracteres *Campo obligatorio</span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-3 col-xs-12 control-label">Descripcion</label>
                                <div class="col-md-6 col-xs-12">
                                    <div class="input-group">
                                        <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                        {{ form.descripcion }}
                                    </div>
                                    <span class="help-block">Longitud maxima 500 caracteres *Campo obligatorio</span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-3 col-xs-12 control-label"> Cliente del Proyecto </label>
                                <div class="col-md-6 col-xs-12">
                                    <div class="input-group">
                                        <span class="input-group-addon"><span class="fa fa-user"></span></span>
                                        {{ form.cliente}}
                                    </div>
                                    <span class="help-block">Seleccione un cliente para el proyecto *Campo obligatorio</span>
                                </div>
                            </div>


                            {{ form.errors }}
                            <div class="panel-footer">
                                <button class="btn btn-primary pull-right"  data-box="#mb-usercreate">Guardar cambios</button>
                            </div>

                        </div>
                    </div>
                </form>

            </div>
        </div>

    </div>

{% endblock %}

templates/pro/proyecto_confirm_delete.html
{% extends 'index.html' %}
{% load static %}

{% block index_content %}
    {% if  flag_terminado == True %}
        <div class="panel-heading">
            <h4 style="text-align:right; font-size:100%;" class="col-12 align-right"><strong>Trabajando en:</strong> {{ proyecto.nombre }} </h4>
            <h3 class="panel-title">Todos los User Storys y Sprints fueron completados</h3>
            <br>
        </div>
        <a class="btn btn-success btn-lg" href="{% url 'Proyecto:terminar' proyecto.id %}">Siguiente</a>
    {% else %}
        <div class="panel-heading">
            <h3 class="panel-title">Existen Sprints o User Storys  incompletos, estos seran cancelados si continua</h3>
            <br>
            {% if perms.Proyecto.eliminar_proyecto %}
                <a  href="{% url 'Proyecto:terminar' proyecto.id %}">
                <button class="btn btn-danger btn-rounded btn-sm" ><span class="fa fa-times"></span>Cancelar Proyecto</button></a>

            {% endif %}
        </div>

    {% endif %}

{% endblock %}