Accounts/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.decorators import login_required
from guardian.decorators import permission_required_or_403


# Urls del sistema
app_name = 'Accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('roles/', views.ListaRoles.as_view(), name='listaRol'),
    path('crear/', views.CrearRol.as_view(), name='crearRol'),
    path('crearPr/', views.CrearRolPr.as_view(), name='crearRolPr'),
    path('<int:pk>/modificar/', views.ModificarRoles.as_view(), name='modificarRol'),
    path('<int:pk>/modificarPr/', views.ModificarRolesProyecto.as_view(), name='modificarRolPr'),
    path('<int:pk>/eliminar/', views.EliminarRol.as_view(), name='eliminarRol'),
    path('<int:pk>/asignar_rol', views.asignarRol.as_view(), name='asignarRol'),
    # path('<int:pk>/eliminar/', views.EliminarRol.as_view(), name='eliminarRol'),
    path('proyectos/list', views.pro_list, name='pro_list'),
    path('usuarios/crear', views.user_mincrear.as_view(), name='user_createmin'),
    path('usuarios/listar', views.ListaUsuarios.as_view(), name='user_listar'),
    path('usuarios/<int:pk>/modificar/', views.ModUser.as_view(), name='user_modificar'),
    path('usuarios/<int:pk>/eliminar/', views.DelUsuarios.as_view(), name='user_eliminar'),
    path('usuarios/<int:pk>/cambiarPass/', views.CambiarPassView.as_view(), name='password_change'),
    path('resetPass/', views.ResetPassView.as_view(), name='password_reset'),
    path('resetPassDone/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='my_password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url=reverse_lazy('Accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete')
]

Cliente/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'Cliente'

urlpatterns = [
    path('cliente/add', views.ClienteCreate.as_view(), name='cliente-add'),
    path('cliente/list', views.ListaClientes.as_view(), name='cliente-list'),
    path('cliente/<int:pk>/modificar', views.ClienteUpdate.as_view(), name='cliente_modificar'),
    path('cliente/<int:pk>/eliminar', views.ClienteDelete.as_view(), name='cliente_eliminar'),
]

IS2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView


from Accounts.forms import LoginForm

urlpatterns = [
    path('clientes/', include('Cliente.urls')),
    path('access/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}),
    path('logout/', views.logout, {'next_page': '/login'}, name='logout'),
    path('', include('Accounts.urls')),
    path('proyecto/', include('Proyecto.urls')),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto/urls.py
from django.urls import path,include
from . import views
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from guardian.decorators import permission_required_or_403


# Urls del sistema
app_name = 'Proyecto'
urlpatterns = [
    path('', views.ListaProyectos.as_view(), name='listaProyectos'),
    path('crear/', views.Crear_Proyecto.as_view(), name='crearProyecto'),
    path('<int:pk>/modificar/', views.Modificar_Proyecto.as_view(), name='modificarProyecto'),
    path('<int:pk>/home/', views.HomeProyectos.as_view(), name='homeProyecto'),

    path('<int:pk>/modificar/team/', include('team.urls')),
    path('<int:pk>/sprint/', include('Sprint.urls')),
    path('<int:pk>/kanban/', include('Kanban.urls')),
    path('<int:pk>/modificar/userstories/', include('UserStory.urls')),
    path('projects/list', views.ListaProyectos, name='pro_list'),
    path('proyecto/crear', views.Crear_Proyecto.as_view(), name='pro_crear'),
    path('<int:pk>/confirmar_terminar', views.VerificarTerminarProyecto.as_view(), name='confirmar_terminarProyecto'),
    path('<int:pk>/terminar', views.CancelarProyecto, name='terminar'),
    path('<int:pk>/iniciar', views.iniciarProyectoView, name='iniciarProyecto'),

    path('<int:pk>/reporte/product_backlog', views.reporte_product_backlog, name='reporteProductBacklog'),
    path('<int:pk>/reporte/horas_totales', views.reporte_horas_trabajadas, name='reporteHorasTrabajadas'),
    path('<int:pk>/reporte/kanban', views.reporte_kanban_actual, name='reporteKanban'),

    # url(r'^team/', include('team.urls', namespace='Team'))
]

templates/base.html
<!-- templates/base.html -->
{% load staticfiles%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %} Gestpro {% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}"/>

{#    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">#}
{#    <link href="{% static "bootstrap/css/local.min.css" %}" rel="stylesheet">#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
        {% block meta_css %} {% endblock %}
    <!--[if lt IE 9]>

      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    {% block meta_js %}
    {% endblock %}
    <![endif]-->

{#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>#}
{#<script src="https://code.jquery.com/jquery-1.12.4.js"></script>#}
{#  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>#}
{#<script type="text/javascript" src="{% static "js/plugins/jquery/jquery.min.js"%}"></script>#}
{#        <script type="text/javascript" src="{% static "js/plugins/jquery/jquery-ui.min.js"%}"></script>#}



    {% block head %}
    {% endblock %}
</head>
    <body>
    {% block content %}
    {% endblock %}
    {% block message %}
    {% endblock %}
    {% block extra %}
    {% endblock %}

        <!-- All that javascript -->
{#        <script src=" {% static "https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" %}"></script>#}
{#        <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>#}

{#        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>#}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>

        {% block scripts %}
        {% endblock %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Bienvenido {{ user.username }}
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>No has iniciado sesión</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block meta_css %}
    <link rel="stylesheet" type="text/css" id="theme" href="{% static "css/theme-default.css" %}">
{% endblock %}

{% block content %}
 <div class="page-container">
    <!-- START PAGE SIDEBAR -->
            <div class="page-sidebar">
                <!-- START X-NAVIGATION -->
                <ul class="x-navigation">
                    <li class="xn-logo">
                        <a href="">Gestpro</a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>
                    <li class="xn-profile">
                        <a href="#" class="profile-mini">
                            <img src="/staticfiles/assets/images/users/avatar.png" alt="John Doe"/>
                        </a>
                        <div class="profile">
                            <div class="profile-image">
                                <img src="/staticfiles/assets/images/users/avatar.png" alt="John Doe"/>
                            </div>
                            <div class="profile-data">
                                <div class="profile-data-name">{{ user.username }}</div>
                                <div class="profile-data-title">{{ user.rol }}</div>
                            </div>
                       <div class="profile-controls">
                    <a href="{% url 'Accounts:user_modificar' user.id %}" class="profile-control-left"><span class="fa fa-info"></span></a>
                         </div>
                        </div>
                    </li>
                    <li class="xn-title">Navigation</li>
                    <li class="xn-openable">
                        <a href="#"><span class="fa fa-files-o"></span> <span class="xn-text">Proyectos</span></a>
                        <ul>
                            {% if perms.Proyecto.crear_proyecto %}
                            <li><a href="{% url 'Proyecto:pro_crear' %}"><span class="fa fa-plus"></span> Crear</a></li>
                            {% endif %}
                            <li><a href="{% url 'Proyecto:listaProyectos' %}"><span class="fa fa-list-ol"></span> Listar</a></li>

                        </ul>
                    </li>
                    <li class="xn-openable">
                        <a href="#"><span class="fa fa-user"></span> <span class="xn-text">Usuarios</span></a>
                        <ul>
                            {% if perms.Proyecto.crear_usuario %}
                            <li><a href="{% url 'Accounts:user_createmin' %}"><span class="fa fa-plus"></span> Crear</a></li>
                            {% endif %}
                            <li><a href="{% url 'Accounts:user_listar' %}"><span class="fa fa-list-ol"></span> Listar</a></li>
                        </ul>
                    </li>

                    {% if perms.Accounts.crear_rol or perms.Accounts.ver_rol or perms.Accounts.crear_rol %}
                    <li class="xn-openable">
                        <a href="#"><span class="fa fa-eye"></span> <span class="xn-text">Roles</span></a>
                        <ul>
	                        {% if 'Accounts.crear_rol' in perms %}
                                <li><a href="{% url 'Accounts:crearRol' %}"><span class="fa fa-plus"></span> Crear Roles de Sistema</a></li>
                            {% endif %}
                             {% if perms.Accounts.crear_rol %}
                            <li><a href="{% url 'Accounts:crearRolPr' %}"><span class="fa fa-plus"></span> Crear Roles de Proyecto</a></li>
                            {% endif %}
                            {% if perms.Accounts.ver_rol %}
                            <li><a href="{% url 'Accounts:listaRol' %}"><span class="fa fa-list-ol"></span> Listar roles</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    {% endif %}

                    <li class="xn-openable">
                        <a href="#"><span class="fa fa-star"></span> <span class="xn-text">Clientes</span></a>
                        <ul>
                            {% if perms.Proyecto.crear_cliente %}
                            <li><a href="{% url 'Cliente:cliente-add' %}"><span class="fa fa-plus"></span> Crear</a></li>
                            {% endif %}
                            <li><a href="{% url 'Cliente:cliente-list' %}"><span class="fa fa-list-ol"></span> Listar</a></li>
                        </ul>
                    </li>


                    <li class="xn-icon-button pull-right">
                        <a href="#" class="mb-control" data-box="#mb-signout"><span class="fa fa-sign-out"></span><span class="xn-text">Logout</span></a>
                    </li>

                </ul>
            </div>

      <!-- PAGE CONTENT -->
    <div class="page-content">
         <!-- START X-NAVIGATION VERTICAL -->
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                    <!-- TOGGLE NAVIGATION -->
                    <li class="xn-icon-button">
                        <a href="#" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
                    </li>
                    <li> {% block barra-superior %}
                    {% endblock %}</li>

                </ul>
                    <!-- END TOGGLE NAVIGATION -->

                <br style="line-height: 5">

{#                <ul class="breadcrumb">#}
{#                    <li><a href="#">Home</a></li>#}
{#                    <li class="active">Dashboard</li>#}
{#                </ul>#}
                <!-- END BREADCRUMB -->
        <!-- PAGE TITLE -->

{#        <div class="page-title">#}
{#            <h2><span class="fa fa-arrow-circle-o-left"></span>{% block page_title %}{% endblock %}</h2>#}
{#        </div>#}
        <!-- END PAGE TITLE -->
        <!-- PAGE CONTENT WRAPPER -->
        <div class="page-content-wrap">
            {% block index_content %}

            {% endblock %}
        </div>

    </div>

</div>
{% endblock %}


{% block extra %}
     <!-- MESSAGE BOX-->
        <div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
            <div class="mb-container">
                <div class="mb-middle">
                    <div class="mb-title"><span class="fa fa-sign-out"></span> Log <strong>Out</strong> ?</div>
                    <div class="mb-content">
                        <p>Estas seguro que deseas cerrar sesión?</p>
                        <p>Presione 'No' si queres seguir trabajando. Presiona 'Si' para cerrar sesión.</p>
                    </div>
                    <div class="mb-footer">
                        <div class="pull-right">
                            <a href="{% url 'logout' %}" class="btn btn-success btn-lg">Si</a>
                            <button class="btn btn-default btn-lg mb-control-close">No</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END MESSAGE BOX-->
{% endblock %}

{% block scripts %}
    {% block page_scripts %}
    {% endblock %}
 <!-- START PRELOADS -->
        <audio id="audio-alert" src="{% static "audio/alert.mp3"%}" preload="auto"></audio>
        <audio id="audio-fail" src="{% static "audio/fail.mp3"%}" preload="auto"></audio>
        <!-- END PRELOADS -->
    <!-- START SCRIPTS -->
        <!-- START PLUGINS -->
        <script type="text/javascript" src="{% static "js/plugins/jquery/jquery.min.js"%}"></script>
        <script type="text/javascript" src="{% static "js/plugins/jquery/jquery-ui.min.js"%}"></script>
        <script type="text/javascript" src="{% static "js/plugins/bootstrap/bootstrap.min.js"%}"></script>
        <!-- END PLUGINS -->
          <!-- START THIS PAGE PLUGINS-->
        <script type='text/javascript' src="{% static 'js/plugins/icheck/icheck.min.js' %}"></script>
        <script type="text/javascript" src="{% static "js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"%}"></script>
        <script type="text/javascript" src="{% static "js/plugins/scrolltotop/scrolltopcontrol.js"%}"></script>

        <script type="text/javascript" src="{% static "js/plugins/morris/morris.min.js"%}"></script>
        <script type="text/javascript" src="{% static "js/plugins/rickshaw/d3.v3.js"%}"></script>
        <script type="text/javascript" src="{% static "js/plugins/rickshaw/rickshaw.min.js"%}"></script>
        <script type='text/javascript' src="{% static 'js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'%}"></script>
        <script type='text/javascript' src="{% static 'js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js'%}"></script>
        <script type='text/javascript' src="{% static 'js/plugins/bootstrap/bootstrap-datepicker.js'%}"></script>
        <script type="text/javascript" src="{% static "js/plugins/owl/owl.carousel.min.js"%}"></script>

        <script type="text/javascript" src="{% static "js/plugins/moment.min.js"%}"></script>
        <script type="text/javascript" src="{% static "js/plugins/daterangepicker/daterangepicker.js"%}"></script>
        <!-- END THIS PAGE PLUGINS-->

        <!-- START TEMPLATE -->

        <script type="text/javascript" src="{% static "js/plugins.js"%}"></script>
        <script type="text/javascript" src="{% static "js/actions.js"%}"></script>
        <!-- END TEMPLATE -->
{#            <script type="text/javascript" src="{% static "js/settings.js" %}"></script>#}

        <script type="text/javascript" src="{% static "js/plugins/bootstrap/bootstrap-select.js"%}"></script>
        <script type="text/javascript" src="{% static "js/demo_tasks.js" %}"></script>

{% endblock %}

templates/login.html
{% extends 'base.html' %}


{% load static %}

{% block title %}Login | {{ block.super }}{% endblock%}

{% block meta_css %}
    <link rel="stylesheet" type="text/css" id="theme" href="{% static "css/theme-default.css" %}">

{% endblock %}

{% block content %}
    {% if form.errors %}

        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
        {% if not user.is_authenticated %}

        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
         {% endif %}
    {% endif %}
        <div class="login-container">

            <div class="login-box animated fadeInDown">
                <div class="login-logo"></div>
                <div class="login-body">
                    <div class="login-title"><strong>Welcome</strong>, Please login</div>
                    <form action="" class="form-horizontal" method="post">
                        {% csrf_token %}
                    <div class="form-group">
                        <div class="col-md-12">
                          {{ form.username }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                           {{ form.password }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <a href="{%  url 'Accounts:password_reset' %}" class="btn btn-link btn-block">Forgot your password?</a>
                        </div>
                        <div class="col-md-6">
                            <button class="btn btn-info btn-block">Log In</button>
                        </div>
                    </div>
                    </form>
                </div>
                <div class="login-footer">
                    <div class="pull-left">
                        &copy; 2018 Gestpro
                    </div>
                </div>
            </div>

        </div>
{% endblock %}

templates/password_change_form.html
{% extends 'base.html' %}

{% block content %}

    hiqowpeafjñkoqiwpeajfdsñ
    {{ form.as_p }}
    <input type="submit">
{% endblock %}

templates/password_reset_complete.html
{% extends 'base.html' %}


{% load static %}

{% block title %}Login | {{ block.super }}{% endblock%}


{% block meta_css %}
    <link rel="stylesheet" type="text/css" id="theme" href="{% static "css/theme-default.css" %}">
     <style>
    label{
        color : white
    }
    </style>
{% endblock %}

{% block content %}

        <div class="login-container">

            <div class="login-box animated fadeInDown">
                <div class="login-logo"></div>
                <div class="login-body">
                    <div class="login-title"> Se completó el restablecimiento de contraseña.
                        <p>Por favor <a href="{% url 'login' %}">inicie sesión</a></p>

                </div>
                <div class="login-footer">
                    <div class="pull-left">
                        &copy; 2018 Gestpro
                    </div>
                </div>
            </div>

        </div>
{% endblock %}

templates/password_reset_confirm.html
{% extends 'base.html' %}


{% load static %}

{% block title %}Login | {{ block.super }}{% endblock%}

{% block meta_css %}
    <link rel="stylesheet" type="text/css" id="theme" href="{% static "css/theme-default.css" %}">

{% endblock %}

{% block content %}
  ¿
        <div class="login-container">

            <div class="login-box animated fadeInDown">
                <div class="login-logo"></div>
                <div class="login-body">
                    <div class="login-title"><strong>Bienvenido de nuevo</strong>, por favor ingrese su nueva contraseña</div>
                    <form action="" class="form-horizontal" method="post">
                        {% csrf_token %}
                    <div class="form-group">
                        <div class="col-md-12">
                            <span style="color: #ffffff;">Nueva contraseña </span>{{ form.new_password1 }}
                        </div>
                    </div>
                         <div class="form-group">
                        <div class="col-md-12">
                            <span style="color: #ffffff;">Confirmación </span>  {{ form.new_password2 }}
                        </div>
                    </div>

                        <span style="color: #ffffff;">{{ form.new_password1.errors }} </span>
                        <span style="color: #ffffff;">{{ form.new_password2.errors }} </span>


                    <div class="form-group">
                        <div class="col-md-6">
                            <button class="btn btn-info btn-block">Restablecer</button>
                        </div>
                    </div>
                    </form>
                </div>
                <div class="login-footer">
                    <div class="pull-left">
                        &copy; 2018 Gestpro
                    </div>
                </div>
            </div>

        </div>
{% endblock %}

templates/password_reset_done.html
{% extends 'base.html' %}


{% load static %}

{% block title %}Login | {{ block.super }}{% endblock%}


{% block meta_css %}
    <link rel="stylesheet" type="text/css" id="theme" href="{% static "css/theme-default.css" %}">
     <style>
    label{
        color : white
    }
    </style>
{% endblock %}

{% block content %}

        <div class="login-container">

            <div class="login-box animated fadeInDown">
                <div class="login-logo"></div>
                <div class="login-body">
                    <div class="login-title"> Se ha enviado una solicitud de restablecimiento de contraseña al
                        email proveido.

    <p>Si no lo recibe, revise en su carpeta de spam y asegurese que la dirección ingresada coincida con la
    dirección registrada.</p></div>

                </div>
                <div class="login-footer">
                    <div class="pull-left">
                        &copy; 2018 Gestpro
                    </div>
                </div>
            </div>

        </div>
{% endblock %}

templates/password_reset_email.html
Alguien solicitó restablecer la contraseña de {{ email }}. Sigue el link y elige una nueva contraseña:
{{ protocol}}://{{ domain }}{% url 'Accounts:password_reset_confirm' uidb64=uid token=token %}

templates/password_reset_form.html
{% extends 'base.html' %}


{% load static %}

{% block title %}Login | {{ block.super }}{% endblock%}


{% block meta_css %}
    <link rel="stylesheet" type="text/css" id="theme" href="{% static "css/theme-default.css" %}">
     <style>
    label{
        color : white
    }
    </style>
{% endblock %}

{% block content %}

        <div class="login-container">

            <div class="login-box animated fadeInDown">
                <div class="login-logo"></div>
                <div class="login-body">
                    <div class="login-title">Ingrese el mail asociado a su cuenta</div>
                    <form action="" class="form-horizontal" method="post">
                        {% csrf_token %}
                    <div class="form-group">
                        <div class="col-md-12">
                          {{ form }}
                        </div>
                    </div>
{#                    <div class="form-group">#}
{#                        <div class="col-md-12">#}
{#                           {{ form.password }}#}
{#                        </div>#}
{#                    </div>#}
                    <div class="form-group">

                        <div class="col-md-6">
                            <button class="btn btn-info btn-block">Restablecer</button>
                        </div>
                    </div>
                    </form>
                </div>
                <div class="login-footer">
                    <div class="pull-left">
                        &copy; 2018 Gestpro
                    </div>
                </div>
            </div>

        </div>
{% endblock %}