Accounts/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth.decorators import login_required
from guardian.decorators import permission_required_or_403


# Urls del sistema
app_name = 'Accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('roles/', views.ListaRoles.as_view(), name='listaRol'),
    path('crear/', views.CrearRol.as_view(), name='crearRol'),
    path('crearPr/', views.CrearRolPr.as_view(), name='crearRolPr'),
    path('<int:pk>/modificar/', views.ModificarRoles.as_view(), name='modificarRol'),
    path('<int:pk>/modificarPr/', views.ModificarRolesProyecto.as_view(), name='modificarRolPr'),
    path('<int:pk>/eliminar/', views.EliminarRol.as_view(), name='eliminarRol'),
    path('<int:pk>/asignar_rol', views.asignarRol.as_view(), name='asignarRol'),
    # path('<int:pk>/eliminar/', views.EliminarRol.as_view(), name='eliminarRol'),
    path('proyectos/list', views.pro_list, name='pro_list'),
    path('usuarios/crear', views.user_mincrear.as_view(), name='user_createmin'),
    path('usuarios/listar', views.ListaUsuarios.as_view(), name='user_listar'),
    path('usuarios/<int:pk>/modificar/', views.ModUser.as_view(), name='user_modificar'),
    path('usuarios/<int:pk>/eliminar/', views.DelUsuarios.as_view(), name='user_eliminar'),
    path('usuarios/<int:pk>/cambiarPass/', views.CambiarPassView.as_view(), name='password_change'),
    path('resetPass/', views.ResetPassView.as_view(), name='password_reset'),
    path('resetPassDone/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='my_password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url=reverse_lazy('Accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete')
]

IS2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView


from Accounts.forms import LoginForm

urlpatterns = [
    path('clientes/', include('Cliente.urls')),
    path('access/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}),
    path('logout/', views.logout, {'next_page': '/login'}, name='logout'),
    path('', include('Accounts.urls')),
    path('proyecto/', include('Proyecto.urls')),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/user/email_pass.html
{% autoescape off %}
Hola {{ user.username }},
    Te damos la bienvenida a Gestpro,
        Los datos para iniciar sesión son:
            usuario: {{ user.username }}
            contraseña: {{ password }}
    Te pedimos que completes tu perfil al iniciar sesión.
    Puedes modificar tu nombre de usuario y contraseña al completar el perfil.
{% endautoescape %}

templates/user/user_confirm_delete.html
{% extends 'index.html' %}
{% block message %}
 <div class="message-box animated fadeIn" data-sound="alert" id="mb-signocreut" method="Post">
            <div class="mb-container">
                <div class="mb-middle">
                    <div class="mb-title"><span class="fa fa-sign-out"></span> Borrar Usuario</strong> ?</div>
                    <div class="mb-content">
                        <p>Estas seguro que queres borrar el usuario?</p>
                    </div>
                    <div class="mb-footer">
                        <div class="pull-right">
                            <input type="submit" class="btn btn-success btn-lg" value="Confirm" />
                            <button class="btn btn-default btn-lg mb-control-close">No</button>
                        </div>
                    </div>
                </div>
            </div>
 </div>
{% endblock %}

templates/user/user_createmin.html
{% extends 'index.html' %}
{% load static %}

{% block index_content %}
<!-- PAGE CONTENT WRAPPER -->
                <div class="page-content-wrap">

                    <div class="row">
                        <div class="col-md-12">

                            <form class="form-horizontal" method="post" >
                                {% csrf_token %}
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title"><strong>Crear usuario</strong></h3>
                                </div>

                                <div class="panel-body">

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Username</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                 {{ form.username }}
                                            </div>
                                            <span class="help-block">Longitud maxima 10 caracteres</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Email</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.email }}
                                            </div>
                                            <span class="help-block">Introduzca su direccion de correo electronico</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Rol de Sistema</label>
                                        <div class="col-md-6 col-xs-12">
                                                {{ form.groups }}

                                        </div>
                                    </div>
                                    {{ form.errors }}

                                    <div class="panel-footer">
                                        <button class="btn btn-default">Clear</button>
                                        <button class="btn btn-primary pull-right"  data-box="#mb-usercreate">Guardar</button>
                                </div>
                                </div>
                            </div>
                            </form>

                        </div>
                    </div>

                </div>
                <!-- END PAGE CONTENT WRAPPER -->
            </div>
            <!-- END PAGE CONTENT -->
        </div>
        <!-- END PAGE CONTAINER -->
{% endblock %}

{% block extra %}
    {{ block.super }}

        <!-- MESSAGE BOX-->
        <div class="message-box animated fadeIn" data-sound="alert" id="mb-usercreate">
            <div class="mb-container">
                <div class="mb-middle">
                    <div class="mb-title"><span class="fa fa-sign-out"></span><strong>Usuario creado</strong></div>
                    <div class="mb-content">
                        <p>Se ha enviado la contraseña al mail provisto</p>
                    </div>
                    <div class="mb-footer">
                        <div class="pull-right">
                            <button class="btn btn-default btn-lg mb-control-close">Ok</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END MESSAGE BOX-->
{% endblock %}

templates/user/user_listar.html
{% extends 'index.html' %}
{% load static %}

{% block index_content %}
    {% load guardian_tags %}
<!-- START RESPONSIVE TABLES -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default">

                                <div class="panel-heading">
                                    <h3 class="panel-title"><strong>Usuarios</strong></h3>
                                    <input class="form-control" id="myInput" type="text" placeholder="Buscar usuario">
                                    <br>
                                </div>

                                <div class="panel-body panel-body-table">

                                    <div class="table-responsive">
                                        <table class="table table-bordered table-striped table-actions">
                                            <thead>
                                                <tr>
                                                    <th>Username</th>
                                                    <th width="100">Email</th>
                                                    <th width="100">Nombre</th>
                                                    <th width="100">Apellido</th>
                                                    <th width="100">Telefono</th>
                                                    <th width="100">Direccion</th>
                                                    <th width="100">Sexo</th>
                                                    <th width="100">Fecha de nacimiento</th>
                                                    <th width="100">Rol de sistema</th>
                                                </tr>
                                            </thead>
                                            <tbody id="myTable">
                                            {% for user in my_users %}
                                                {% if user.username != 'AnonymousUser' %}
                                                    <tr id="{{ user.id }}">
                                                        <td><strong>{{ user.username }}</strong></td>
                                                        <td><span class="text-center">{{ user.email }}</span></td>
                                                        <td><span class="text-center">{{ user.first_name }}</span></td>
                                                        <td><span class="text-center">{{ user.last_name }}</span></td>
                                                        <td><span class="text-center">{{ user.phone }}</span></td>
                                                        <td><span class="text-center">{{ user.address }}</span></td>
                                                        <td><span class="text-center">{{ user.gender }}</span></td>
                                                        <td><span class="text-center">{{ user.date_birth }}</span></td>
                                                      <td><span class="text-center">
                                                        {% for rol in user.groups.all %}
                                                            {{ rol.name }}
                                                        {% endfor %}
                                                    </span></td>
                                                        <td>
                                                           <a href="{% url 'Accounts:user_modificar' user.id %}"><button class="btn btn-default btn-rounded btn-sm"><span class="fa fa-pencil"></span></button></a>
                                                            <a href="{% url 'Accounts:user_eliminar' user.id %}"><button class="btn btn-danger btn-rounded btn-sm" ><span class="fa fa-times"></span></button></a>
                                                        </td>
                                                    </tr>
                                                {% endif %}
                                             {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>

                                </div>
                            </div>

                        </div>
                    </div>
                    <!-- END RESPONSIVE TABLES -->
{% endblock %}

{% block page_scripts %}
      <!-- START THIS PAGE PLUGINS-->
        <script type='text/javascript' src="{% static 'js/plugins/icheck/icheck.min.js'%}"></script>
        <script type="text/javascript" src="{% static "js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"%}"></script>

        <script type="text/javascript" src="{% static "js/demo_tables.js" %}"></script>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
        <!-- END THIS PAGE PLUGINS-->
{% endblock %}

templates/user/user_mod.html
{% extends 'index.html' %}
{% load static %}

{% block index_content %}
<!-- PAGE CONTENT WRAPPER -->
                <div class="page-content-wrap">

                    <div class="row">
                        <div class="col-md-12">

                            <form class="form-horizontal" method="post" >
                                {% csrf_token %}
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title"><strong>Crear usuario</strong></h3>
                                </div>

                                <div class="panel-body">

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Username</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                 {{ form.username }}
                                            </div>
                                            <span class="help-block">Longitud maxima 50 caracteres</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Email</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.email }}
                                            </div>
                                            <span class="help-block">Introducir direccion de correo electronico</span>
                                        </div>
                                    </div>
                                      <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Nombre</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.first_name }}
                                            </div>
                                            <span class="help-block">Longitud maxima de 80 caracteres</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Apellido</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.last_name }}
                                            </div>
                                            <span class="help-block">Longitud maxima de 80 caracteres</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Telefono</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.phone }}
                                            </div>
                                            <span class="help-block">Introduzca su numero telefonico</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Direccion</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.address }}
                                            </div>
                                            <span class="help-block">Longitud maxima de 80 caracteres</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Sexo</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.gender }}
                                            </div>
                                            <span class="help-block">M: masculino o F: femenino</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Fecha de Nacimiento</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.date_birth }}
                                            </div>
                                            <span class="help-block">Formato AAAA/MM/DD</span>
                                        </div>
                                    </div>
                                   <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Rol de sistema asignado</label>
                                        <div class="col-md-6 col-xs-12">
                                                {{ form.groups }}

                                        </div>
                                    </div>
                                    <div class="panel-footer">
                                        <button class="btn btn-primary pull-right"  data-box="#mb-usercreate">Guardar</button>
                                </div>
                                </div>
                            </div>
                            </form>

                        </div>
                    </div>

                </div>
                <!-- END PAGE CONTENT WRAPPER -->
            </div>
            <!-- END PAGE CONTENT -->
        </div>
        <!-- END PAGE CONTAINER -->
{% endblock %}

    <!-- MESSAGE BOX-->
        <div class="message-box animated fadeIn" data-sound="alert" id="mb-usercreate">
            <div class="mb-container">
                <div class="mb-middle">
                    <div class="mb-title"><span class="fa fa-sign-out"></span><strong>Usuario creado</strong></div>
                    <div class="mb-content">
                        <p>Se ha enviado la contraseña al mail provisto</p>
                    </div>
                    <div class="mb-footer">
                        <div class="pull-right">
                            <button class="btn btn-default btn-lg mb-control-close">Ok</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END MESSAGE BOX-->