Cliente/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'Cliente'

urlpatterns = [
    path('cliente/add', views.ClienteCreate.as_view(), name='cliente-add'),
    path('cliente/list', views.ListaClientes.as_view(), name='cliente-list'),
    path('cliente/<int:pk>/modificar', views.ClienteUpdate.as_view(), name='cliente_modificar'),
    path('cliente/<int:pk>/eliminar', views.ClienteDelete.as_view(), name='cliente_eliminar'),
]

IS2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView


from Accounts.forms import LoginForm

urlpatterns = [
    path('clientes/', include('Cliente.urls')),
    path('access/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}),
    path('logout/', views.logout, {'next_page': '/login'}, name='logout'),
    path('', include('Accounts.urls')),
    path('proyecto/', include('Proyecto.urls')),
]

if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cliente/models.py
from django.db import models
from django.urls import reverse


class Cliente(models.Model):
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    cedula = models.CharField(max_length=15, unique=True)
    direccion = models.CharField(max_length=200, null=True, blank=True)
    telefono = models.CharField(max_length=10, null=True, blank=True)
    email = models.EmailField(max_length=100,unique=True)

    def get_absolute_url(self):
        return reverse('Cliente:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.nombre + ' ' + self.apellido

    class Meta:
        default_permissions = []
        permissions = (
            ("crear_cliente", "Crear clientes"),
            ("modificar_cliente", "Modificar clientes"),
            ("eliminar_cliente", "Eliminar clientes")
        )

Cliente/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'apellido', 'cedula', 'direccion', 'telefono', 'email']

Cliente/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin

from .models import Cliente
"""
    ClienteCreate hereda de de la vista generica CreateView y PermissionRequiredMixin
    Requiere que el usuario posea el  permiso crear_cliente para poder ser utilizada
"""
class ClienteCreate(PermissionRequiredMixin, CreateView):
    model = Cliente
    template_name = 'clientes/cliente_create.html'
    fields = ['nombre', 'apellido', 'cedula', 'direccion', 'telefono', 'email']
    permission_required = 'Cliente.crear_cliente'
    raise_exception = True
    success_url = reverse_lazy('Cliente:cliente-list')

"""
       ClienteUpdate hereda de de la vista generica UpdateView y PermissionRequiredMixin
       Requiere que el usuario posea el  permiso modificar_cliente para poder ser utilizada
"""
class ClienteUpdate(PermissionRequiredMixin, UpdateView):
    model = Cliente
    template_name = 'clientes/cliente_mod.html'
    fields = ['nombre', 'apellido','cedula', 'direccion', 'telefono', 'email']
    permission_required = 'Cliente.modificar_cliente'
    raise_exception = True
    success_url = reverse_lazy('Cliente:cliente-list')


class ListaClientes(ListView):
    model = Cliente
    context_object_name = 'my_clients'
    template_name = 'clientes/clientes_listar.html'

"""
       ClienteDelete hereda de de la vista generica DeleteView y PermissionRequiredMixin
       Requiere que el usuario posea el permiso eliminar_cliente para poder ser utilizada
"""
class ClienteDelete(PermissionRequiredMixin, DeleteView):
    model = Cliente
    template_name = 'clientes/clientes_listar.html'
    permission_required = 'Cliente.eliminar_cliente'
    raise_exception = True
    success_url = reverse_lazy('Cliente:cliente-list')

templates/clientes/cliente_create.html
{% extends 'index.html' %}
{% load static %}

{% block index_content %}
<!-- PAGE CONTENT WRAPPER -->
                <div class="page-content-wrap">

                    <div class="row">
                        <div class="col-md-12">

                            <form class="form-horizontal" method="post" >
                                {% csrf_token %}
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title"><strong>Crear cliente</strong></h3>
                                </div>

                                <div class="panel-body">

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Nombre</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                 {{ form.nombre }}
                                            </div>
                                            <span class="help-block">Longitud maxima 100 caracteres  *Campo obligatorio</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Apellido</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.apellido }}
                                            </div>
                                            <span class="help-block">Longitud maxima 100 caracteres *Campo obligatorio</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Cedula</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.cedula }}
                                            </div>
                                            <span class="help-block">Nro. de cedula del cliente *Campo Obligatorio</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Direccion</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.direccion }}
                                            </div>
                                            <span class="help-block">Longitud maxima 200 caracteres</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Telefono</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.telefono }}
                                            </div>
                                            <span class="help-block">Nro. de telefono del cliente</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Email</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.email }}
                                            </div>
                                            <span class="help-block">Direccion de correo electronico del cliente *Campo obligatorio</span>
                                        </div>
                                    </div>

                                    <div class="panel-footer">
                                        <button class="btn btn-primary pull-right"  data-box="#mb-usercreate">Crear</button>

                                    </div>
                                </div>
                            </div>
                            </form>

                        </div>
                    </div>

                </div>
                <!-- END PAGE CONTENT WRAPPER -->
            </div>
            <!-- END PAGE CONTENT -->
        </div>
        <!-- END PAGE CONTAINER -->
{% endblock %}

{% block message %}
        <!-- MESSAGE BOX-->
        <div class="message-box animated fadeIn" data-sound="alert" id="mb-usercreate">
            <div class="mb-container">
                <div class="mb-middle">
                    <div class="mb-title"><span class="fa fa-address-book-o"></span><strong>Cliente creado</strong></div>
                    <div class="mb-content">
                        <p>Se ha creado un nuevo registro en la base de datos</p>
                    </div>
                    <div class="mb-footer">
                        <div class="pull-right">
                            <button class="btn btn-default btn-lg mb-control-close">Ok</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END MESSAGE BOX-->
{% endblock %}

templates/clientes/cliente_mod.html
{% extends 'index.html' %}
{% load static %}

{% block index_content %}
<!-- PAGE CONTENT WRAPPER -->
                <div class="page-content-wrap">

                    <div class="row">
                        <div class="col-md-12">

                            <form class="form-horizontal" method="post" >
                                {% csrf_token %}
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title"><strong>Crear Cliente</strong></h3>
                                </div>

                                <div class="panel-body">

                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Nombre</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                 {{ form.nombre }}
                                            </div>
                                            <span class="help-block">Nombre del Cliente *Campo Obligatorio</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Apellido</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.apellido }}
                                            </div>
                                            <span class="help-block">Apellido del Cliente *Campo Obligatorio</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Cedula</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.cedula }}
                                            </div>
                                            <span class="help-block">Nro. de Cedula del Cliente *Campo Obligatorio</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Direccion</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.direccion }}
                                            </div>
                                            <span class="help-block">Direccion del Cliente</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Telefono</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.telefono }}
                                            </div>
                                            <span class="help-block">Nro. de Telefono del Cliente</span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-3 col-xs-12 control-label">Email</label>
                                        <div class="col-md-6 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                                                {{ form.email }}
                                            </div>
                                            <span class="help-block">Correo Electronico del Clinete *Campo Obligatorio</span>
                                        </div>
                                    </div>

                                    <div class="panel-footer">
                                        <button class="btn btn-primary pull-right"  data-box="#mb-usercreate">Guardar Cambios</button>

                                    </div>
                                </div>
                            </div>

                            </form>

                        </div>
                    </div>

                </div>
                <!-- END PAGE CONTENT WRAPPER -->
            </div>
            <!-- END PAGE CONTENT -->
        </div>
        <!-- END PAGE CONTAINER -->
{% endblock %}

templates/clientes/clientes_listar.html
{% extends 'index.html' %}
{% load static %}

{% block index_content %}
    {% load guardian_tags %}
    <!-- START RESPONSIVE TABLES -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <h3 class="panel-title"><strong>Clientes</strong></h3>
                    <input class="form-control" id="myInput" type="text" placeholder="Buscar cliente">
                    <br>
                </div>

                <div class="panel-body panel-body-table">

                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-actions">
                            <thead>
                            <tr>
                                <th>Nombre</th>
                                <th width="100">Apellido</th>
                                <th width="100">Cedula</th>
                                <th width="100">Direccion</th>
                                <th width="100">Telefono</th>
                                <th width="100">Email</th>
                            </tr>
                            </thead>
                            <tbody id="myTable">
                            {% for client in my_clients %}
                                <tr id="{{ client.id }}">

                                    <td><strong>{{ client.nombre }}</strong></td>
                                    <td><span class="text-center">{{ client.apellido}}</span></td>
                                    <td><span class="text-center">{{ client.cedula}}</span></td>
                                    <td><span class="text-center">{{ client.direccion}}</span></td>
                                    <td><span class="text-center">{{ client.telefono }}</span></td>
                                    <td><span class="text-center">{{ client.email}}</span></td>
                                    <td>
                                         {% if perms.Cliente.modificar_cliente %}
                                        <a href="{% url 'Cliente:cliente_modificar' client.id %}"><button class="btn btn-default btn-rounded btn-sm"><span class="fa fa-pencil"></span></button></a>
                                        {% endif %}
                                        {% if perms.Cliente.eliminar_cliente %}
                                        <a href="#" class="mb-control" data-box="#mb-delete{{ client.id }}">
                                            <button class="btn btn-danger btn-rounded btn-sm" ><span class="fa fa-times"></span></button></a>
                                        {% endif %}
                                    </td>

                                </tr>


                            <div class="message-box animated fadeIn" data-sound="alert" id="mb-delete{{ client.id }}">
                                <div class="mb-container">
                                    <div class="mb-middle">
                                        <div class="mb-title"><span class="fa fa-trash-o"></span><strong>Borrar</strong></div>
                                        <div class="mb-content">
                                            <p>Estas seguro que deseas borrar al cliente {{ client.nombre }} {{ client.apellido }} con id {{ client.id }} ?</p>
                                        </div>
                                        <div class="mb-footer">
                                            <div class="pull-right">
                                                <form action="{% url 'Cliente:cliente_eliminar' client.id %}" method="post">{% csrf_token %}
                                                    <input type="submit" value="Si" class="btn btn-success btn-lg"></input>
                                                    <button class="btn btn-default btn-lg mb-control-close">No</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>

        </div>
    </div>
    <!-- END RESPONSIVE TABLES -->
{% endblock %}

{% block page_scripts %}
    <!-- START THIS PAGE PLUGINS-->
    <script type='text/javascript' src="{% static 'js/plugins/icheck/icheck.min.js'%}"></script>
    <script type="text/javascript" src="{% static "js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"%}"></script>

    <script type="text/javascript" src="{% static "js/demo_tables.js" %}"></script>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
    <!-- END THIS PAGE PLUGINS-->
{% endblock %}